export { Claims } from 'src/ui/home/containers/claims'
export { ClaimDetails } from 'src/ui/home/containers/claimDetails'
export { Records } from 'src/ui/home/containers/records'
export { ShareConsent } from 'src/ui/sso/containers/shareConsent'
export { CredentialReceive } from 'src/ui/home/containers/credentialReceive'
