require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SmartWallet' do
  # Pods for SmartWallet
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'Permission-Notifications', :path => "../node_modules/react-native-permissions/ios/Notifications.podspec"
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"

  # NOTE: this is needed to enable "modular_headers" for JolocomCore!
  # otherwise we would have to use "use_frameworks!"
  # but that interferes with "Flipper" (see notes about flipper at the end)
  pod 'JolocomCore', :path => '../node_modules/@jolocom/native-core-react-native', :modular_headers => true

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'SmartWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SmartWallet-tvOS' do
  # Pods for SmartWallet-tvOS

  target 'SmartWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
