require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'SmartWallet' do
  # Pods for SmartWallet
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'Permission-Notifications', :path => "../node_modules/react-native-permissions/ios/Notifications/Permission-Notifications.podspec"
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera/Permission-Camera.podspec"

  # NOTE: this is needed to enable "modular_headers" for JolocomCore!
  # otherwise we would have to use "use_frameworks!"
  # but that interferes with "Flipper" (see notes about flipper at the end)
  pod 'JolocomCore', :path => '../node_modules/@jolocom/native-core-react-native', :modular_headers => true

  config = use_native_modules!
    use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'react-native-branch', :path => '../node_modules/react-native-branch'

  target 'SmartWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # use_flipper!()

    post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
    end
end
