platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.app.bundle')
  end

  desc 'Fetch certificates. Build the iOS application.'
  lane :build do
    certificates
    gym(
      scheme: "SmartWallet",
      project: './ios/SmartWallet.xcodeproj',
      export_method: 'development'
    )
 end
end
