# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :build do
    match(type: 'appstore')
    build_ios_app(
      scheme: "JolocomWallet",
      export_method: 'app-store',
      include_bitcode: false,
    )
  end

  lane :upload do |options|
    sentry_upload_dsym(
      auth_token: '',
      org_slug: 'jolocom',
      project_slug: 'smartwallet',
    )
    case options[:target]
    when "release"
      upload_to_app_store
    when "beta"
      upload_to_testflight
    end
  end

  desc "Install a release build on an iOS device"
  lane :staging do
    build
    install_on_device(
      skip_wifi: true
    )
  end

  desc "Submit a new beta build to TestFlight"
  lane :beta do
    ensure_git_branch(branch: 'master')
    ensure_git_status_clean
    increment_build_number(xcodeproj: "JolocomWallet.xcodeproj")
    build
    upload(target: "beta")
  end

  desc "Submit a new release build to the App Store"
  lane :release do
    ensure_git_branch(branch: 'master')
    ensure_git_status_clean
    increment_build_number(xcodeproj: "JolocomWallet.xcodeproj")
    build
    upload(target: "release")
  end
end
