export { default as SuccessTick } from './SuccessTickIcon'
export { default as ErrorIcon } from './ErrorIcon'
export { default as HandIcon } from './HandIcon'
export { default as SplashIcon } from './SplashIcon'
export { default as BackArrowIcon } from './BackArrowIcon'
export { default as ForthArrowIcon } from './ForthArrowIcon'
export { default as TorchOnIcon } from './TorchOnIcon'
export { default as TorchOffIcon } from './TorchOffIcon'
