export { termsOfServiceDE } from './termsOfServiceDE'
export { termsOfServiceEN } from './termsOfServiceEN'
export { privacyPolicyDE } from './privacyPolicyDE'
export { privacyPolicyEN } from './privacyPolicyEN'
export { impressumDE } from './impressumDE'
export { impressumEN } from './impressumEN'
