export const enum routeList {
  Landing = 'Landing',
  Consent = 'Consent',
  PasswordEntry = 'PasswordEntry',
  Entropy = 'Entropy',
  Loading = 'Loading',
  SeedPhrase = 'SeedPhrase',
  Home = 'Home',
  Claims = 'Claims',
  Interactions = 'Interactions',
  Exception = 'Exception',
  ClaimDetails = 'ClaimDetails',
  CredentialDialog = 'CredentialDialog',
  QRCodeScanner = 'QRCodeScanner',
}
