// NOTE: Document card
export const ORIGINAL_DOCUMENT_CARD_WIDTH = 320
export const ORIGINAL_DOCUMENT_CARD_HEIGHT = 398
export const ORIGINAL_DOCUMENT_SCREEN_WIDTH = 375

// NOTE: Share card
export const ORIGINAL_DOCUMENT_SHARE_CARD_WIDTH = 368
export const ORIGINAL_DOCUMENT_SHARE_CARD_HEIGHT = 232
export const MAX_FIELD_SHARE_CARD = 2
