# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Play Store"
  lane :beta do  desc "Submit a new Beta Build to Play Store"
    sh("git clone git@infra.jolocom.io:android-secrets")
    password = prompt(
      text: "password: ",
      secure_text: true
    )
    sh("openssl enc -aes-256-cbc -d -in ./android-secrets/secrets.enc -out secrets.json -k #{password}", log: false)
    sh("openssl enc -aes-256-cbc -d -in ./android-secrets/key.enc -out key.json -k #{password}", log: false)
    secrets = load_json(json_path: "./android-secrets/secrets.json")
    releaseFilePath = File.join(Dir.pwd, "..", "android-secrets", "JoloSmartWallet.keystore")
    build_android_app(task: 'clean')
    build_android_app(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => secrets["keystorePassword"],
        "android.injected.signing.key.alias" => "JoloSmartWallet",
        "android.injected.signing.key.password" => secrets["keystorePassword"],
      }
    )
    sentry_upload_dsym(
      auth_token: secrets["sentryAuth"],
      org_slug: 'jolocom',
      project_slug: 'smartwallet',
    )
    upload_to_play_store(
      track: 'internal'
    )
    sh("rm secrets.json")
    sh("rm key.json")
  end
end
