name: Dev Build

on:
  push: 
    tags:
      - t*

jobs:
  make-ios-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Check ruby version
        run: ruby --version
      - name: Check files
        run: |
          ls -la
          cd fastlane
          cat Fastfile
      - name: Build
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: alpha
          subdirectory: ios