name: Dev Build

on:
  push: 
    tags:
      - t*

jobs:
  make-ios-build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check node & npm versions
        run: |
          npm --version
          node --version
      - name: Install modules
        run: yarn install
      # - name: Setup ssh
      #   uses: webfactory/ssh-agent@v0.5.2
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail
      - name: List known hosts
        run: |
          cat /Users/runner/.ssh/known_hosts
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Check ruby version
        run: ruby --version
      - name: Install Pods
        run: |
          cd ios
          pod install
      - name: Build
        run: |
          bundle exec fastlane ios alpha
