name: Dev Build

on:
  push: 
    tags:
      - t*

jobs:
  make-ios-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2p137'
      - name: Check ruby version
        run: ruby --version
      - name: Build
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: alpha
          subdirectory: ios