name: Dev Build

on:
  push: 
    tags:
      - t*

jobs:
  make-ios-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: yarn alpha:ios